services:
    carrerarepository:
        alias: carrerarepository.doctrine
    carrerarepository.inmemory:
        class: App\CorredoresRiojaInfrastructure\InMemoryRepository\CarreraRepository
        public: false
    carrerarepository.doctrine:
        class: App\CorredoresRiojaInfrastructure\InBDRepository\CarreraRepository
        public: false
    corredorrepository:
        alias: corredorrepository.doctrine
    corredorrepository.inmemory:
        class: App\CorredoresRiojaInfrastructure\InMemoryRepository\CorredorRepository
        public: false
    corredorrepository.doctrine:
        class: App\CorredoresRiojaInfrastructure\InBDRepository\CorredorRepository
        public: false
    organizacionrepository:
        alias: organizacionrepository.inmemory
    organizacionrepository.inmemory:
        class: App\CorredoresRiojaInfrastructure\InMemoryRepository\OrganizacionRepository
        public: false
    participanterepository:
        alias: participanterepository.inmemory
    participanterepository.inmemory:
        class: App\CorredoresRiojaInfrastructure\InMemoryRepository\ParticipanteRepository
        public: false        
    corredores_user_provider:
        class : App\CorredoresRiojaBundle\Security\CorredorUserProvider
        arguments : [ "@doctrine.orm.entity_manager" ]
    corredorescontroller:
        class : App\CorredoresRiojaBundle\Controller\CorredoresController
        arguments : [  @twig, "@doctrine.orm.entity_manager" , "@security.authentication_utils", "@form.factory", "@security.encoder_factory",  "@security.token_storage", "@router"]
    
    
#    entryrepository:
#         alias: entryrepository.inmemory
#    entryrepository.inmemory:
#         class: Blog\BlogInfrastructure\Repository\InMemoryEntryRepository
#         public: false

#    app_corredores_rioja.example:
#        class: App\CorredoresRiojaBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
